# Generated by Django 2.2.1 on 2019-06-01 07:32

from django.db import migrations

from IoT_Serwer import models


def create_state_field(apps,schema_editor):
    data = models.CurrentStateData()
    data.save()


class Migration(migrations.Migration):
    dependencies = [
        ('IoT_Serwer', '0001_initial')
    ]

    operations = [
        migrations.RunPython(create_state_field)
    ]
