# Generated by Django 2.2.1 on 2019-06-01 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Serwer', '0002_create_data_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentstatedata',
            name='temperature',
            field=models.FloatField(default=20.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
