# Generated by Django 2.2.1 on 2019-06-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Serwer', '0004_auto_20190606_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentstatedata',
            old_name='shutterState',
            new_name='shutterPosition',
        ),
    ]
