# Generated by Django 2.2.1 on 2019-06-08 15:58

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Serwer', '0005_auto_20190606_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstatedata',
            name='cloudiness',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='currentstatedata',
            name='weather_reading_date_utc',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 15, 58, 22, 518170)),
        ),
    ]
