# Generated by Django 2.2.1 on 2019-06-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Serwer', '0006_auto_20190608_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentstatedata',
            name='weather_reading_date_utc',
            field=models.DateTimeField(null=True),
        ),
    ]
